apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.1.0
        profile:
            VendorType: redhat
            version: v1.0
        chart-uri: https://dperaza4dustbit.github.io/helm-chart/vault-0.12.11.tgz
        digest: sha256:c0a133a4dba73b6f5fc53ae0b4efedfc055b024ac3fe77770142a90a43b3f907
        digests:
            chart: sha256:c0a133a4dba73b6f5fc53ae0b4efedfc055b024ac3fe77770142a90a43b3f907
            package: 49524bccec4a9267efb8084a87f07b23b5f201abef6432c67eb91cd713e63d61
        lastCertifiedTimestamp: "2021-07-07T22:26:39.313674+00:00"
        certifiedOpenShiftVersions: 4.7.0
    chart:
        name: vault
        home: https://www.vaultproject.io
        sources:
          - https://github.com/hashicorp/vault
          - https://github.com/hashicorp/vault-helm
          - https://github.com/hashicorp/vault-k8s
          - https://github.com/hashicorp/vault-csi-provider
        version: 0.12.11
        description: Official HashiCorp Vault Chart
        keywords:
          - vault
          - security
          - encryption
          - secrets
          - management
          - automation
          - infrastructure
        maintainers: []
        icon: https://github.com/hashicorp/vault/raw/f22d202cde2018f9455dec755118a9b84586e082/Vault_PrimaryLogo_Black.png
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 1.7.2
        deprecated: false
        annotations: {}
        kubeversion: '>= 1.14.0-0'
        dependencies: []
        type: ""
    chart-overrides: ""
results:
  - check: v1.0/helm-lint
    type: Mandatory
    outcome: PASS
    reason: Helm lint successful
  - check: v1.0/contains-values
    type: Mandatory
    outcome: PASS
    reason: Values file exist
  - check: v1.0/contains-values-schema
    type: Mandatory
    outcome: PASS
    reason: Values schema file exist
  - check: v1.0/has-kubeversion
    type: Mandatory
    outcome: PASS
    reason: Kubernetes version specified
  - check: v1.0/not-contains-crds
    type: Mandatory
    outcome: PASS
    reason: Chart does not contain CRDs
  - check: v1.0/not-contain-csi-objects
    type: Mandatory
    outcome: PASS
    reason: CSI objects do not exist
  - check: v1.0/has-readme
    type: Mandatory
    outcome: PASS
    reason: Chart has a README
  - check: v1.0/is-helm-v3
    type: Mandatory
    outcome: PASS
    reason: API version is V2, used in Helm 3
  - check: v1.0/contains-test
    type: Mandatory
    outcome: PASS
    reason: Chart test files exist
  - check: v1.0/images-are-certified
    type: Mandatory
    outcome: PASS
    reason: |-
        Image is Red Hat certified : registry.connect.redhat.com/hashicorp/vault-k8s:0.10.1-ubi
        Image is Red Hat certified : registry.connect.redhat.com/hashicorp/vault:1.7.2-ubi
  - check: v1.0/chart-testing
    type: Mandatory
    outcome: PASS
    reason: Chart tests have passed
