apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.0.0
        chart-uri: psql-service-0.1.1.tgz
        digest: sha256:bc5829f903d061df7f0d4e225dcf3ad1508c13f0d7ddd0d5c82c6c5f4215d9f9
        lastCertifiedTimestamp: "2021-05-13T13:45:11.048262-04:00"
        certifiedOpenShiftVersions: 4.7.5
    chart:
        name: psql-service
        home: ""
        sources: []
        version: 0.1.1
        description: A Helm chart for a RedHat Certified PSQL
        keywords: []
        maintainers: []
        icon: ""
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 10.0.0
        deprecated: false
        annotations: {}
        kubeversion: 1.20.0
        dependencies: []
        type: application
    overrides: ""
results:
  - check: contains-values
    type: Mandatory
    outcome: PASS
    reason: Values file exist
  - check: has-kubeversion
    type: Mandatory
    outcome: PASS
    reason: Kubernetes version specified
  - check: helm-lint
    type: Mandatory
    outcome: PASS
    reason: Helm lint successful
  - check: images-are-certified
    type: Mandatory
    outcome: PASS
    reason: 'Image is Red Hat certified : registry.access.redhat.com/rhscl/postgresql-10-rhel7:latest'
  - check: chart-testing
    type: Mandatory
    outcome: PASS
    reason: Chart tests have passed
  - check: has-readme
    type: Mandatory
    outcome: PASS
    reason: Chart has a README
  - check: is-helm-v3
    type: Mandatory
    outcome: PASS
    reason: API version is V2, used in Helm 3
  - check: contains-test
    type: Mandatory
    outcome: PASS
    reason: Chart test files exist
  - check: contains-values-schema
    type: Mandatory
    outcome: PASS
    reason: Values schema file exist
  - check: not-contains-crds
    type: Mandatory
    outcome: PASS
    reason: Chart does not contain CRDs
  - check: not-contain-csi-objects
    type: Mandatory
    outcome: PASS
    reason: CSI objects do not exist
